[package]
name = "bacon-sci"
version = "0.8.4"
authors = ["aftix <aftix@aftix.xyz>"]
edition = "2018"
license="MIT"
description="Scientific computing in Rust"
homepage="https://github.com/aftix/bacon"
repository="https://github.com/aftix/bacon"
readme="README.md"
keywords=["numeric", "science", "integration", "quadrature"]
categories=["science"]

[features]
serialize=["serde"]

[dev-dependencies]
float-cmp="0.8"

[dependencies]
serde={version="1.0", optional=true}
nalgebra="0.24"
num-complex="0.2"
num-traits="0.2"
alga="0.9"
phf = "0.8"

[build-dependencies]
phf_codegen = "0.8"
